"""Render documents from hand-written templates and the results summary.

A template is Markdown whose numbers come only from placeholders:

``{{ key }}`` or ``{{ key | format }}`` or ``{{ key | format:arg:arg }}``
    a metric in the results summary (``results/summary.json``), printed with a
    format from :mod:`report.formats` (by default the one that fits its unit);
``{{ first.key - second.key | pp }}``
    the difference of two metrics with the same unit (a difference of rates
    prints only as percentage points);
``{{ protocol:windows.test.start | date }}``
    a fixed definition from ``experiments/protocol.yaml``;
``{{ config:world:product.down_payment_bps | bps_pct }}``
    a fixed definition from ``config/<name>.yaml``;
``{{ table:name | column "Header" format, column "Header", ... }}``
    on a line of its own: a generated Markdown table from a result table, with
    the columns named (``format`` optional).

Rendering fails, listing every problem with its line, on a missing key, an
unknown format or a format that does not fit the unit. Templates live under
``report/templates/`` at the path of the document they produce (for example
``report/templates/README.md`` produces ``README.md``).
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from core.results import Metric, metric, table
from report import formats
from report.formats import FormatError, Value

REPO = Path(__file__).resolve().parent.parent
TEMPLATES = REPO / "report" / "templates"
SUMMARY = REPO / "results" / "summary.json"
PLACEHOLDER = re.compile(r"\{\{(.*?)\}\}", re.DOTALL)
COLUMN = re.compile(r'^\s*([a-z0-9_]+)\s*(?:"([^"]*)")?\s*([a-z0-9_:]+)?\s*$')
KEY = re.compile(r"^[a-z0-9_]+(\.[a-z0-9_]+)*$")
HEADER = (
    "<!-- Generated by `python -m report render` from {template}. "
    "Edit the template, not this file. -->\n"
)


class RenderError(ValueError):
    """A template could not be rendered; ``problems`` lists each one."""

    def __init__(self, name: str, problems: list[str]):
        self.problems = problems
        super().__init__(f"{name}: " + "; ".join(problems))


@dataclass
class Sources:
    """Where placeholders look values up."""

    summary: Mapping[str, Any]
    protocol: Mapping[str, Any] = field(default_factory=dict)
    configs: Mapping[str, Mapping[str, Any]] = field(default_factory=dict)

    @classmethod
    def from_repo(cls, summary: Mapping[str, Any], root: Path = REPO) -> Sources:
        protocol = yaml.safe_load((root / "experiments" / "protocol.yaml").read_text())
        configs = {
            path.stem: yaml.safe_load(path.read_text())
            for path in sorted((root / "config").glob("*.yaml"))
        }
        return cls(summary=summary, protocol=protocol, configs=configs)


def _path(data: Any, dotted: str, what: str) -> Any:
    node = data
    for part in dotted.split("."):
        if isinstance(node, Mapping) and part in node:
            node = node[part]
        elif isinstance(node, list) and part.isdigit() and int(part) < len(node):
            node = node[int(part)]
        else:
            raise KeyError(f"{what} has no {dotted!r}")
    if isinstance(node, Mapping | list):
        raise KeyError(f"{what} {dotted!r} is not a single value")
    return node


def _resolve(expression: str, sources: Sources) -> Value:
    if expression.startswith("protocol:"):
        return Value(plain=_path(sources.protocol, expression[len("protocol:"):], "the protocol"))
    if expression.startswith("config:"):
        name, _, dotted = expression[len("config:"):].partition(":")
        if name not in sources.configs:
            raise KeyError(f"no configuration file {name!r}")
        return Value(plain=_path(sources.configs[name], dotted, f"config/{name}.yaml"))
    if " - " in expression:
        first, second = (part.strip() for part in expression.split(" - ", 1))
        return _difference(_metric(first, sources), _metric(second, sources))
    return Value(metric=_metric(expression, sources))


def _metric(key: str, sources: Sources) -> Metric:
    if not KEY.fullmatch(key):
        raise KeyError(f"{key!r} is not a result key")
    return metric(sources.summary, key)


def _difference(first: Metric, second: Metric) -> Value:
    if first.unit != second.unit:
        raise FormatError(f"cannot subtract {second.unit} from {first.unit}")
    if not (first.evaluated and second.evaluated):
        raise FormatError("cannot subtract a metric that was not evaluated")
    return Value(plain=first.value - second.value, difference_of=first.unit)


def _split(body: str) -> tuple[str, str, list[str]]:
    expression, _, spec = body.partition("|")
    name, *args = (spec.strip() or "value").split(":")
    return expression.strip(), name.strip(), [arg.strip() for arg in args]


def render_value(body: str, sources: Sources) -> str:
    """Render one inline placeholder body (the text between the braces)."""
    expression, name, args = _split(body)
    return formats.apply(name, _resolve(expression, sources), args)


def render_table(body: str, sources: Sources) -> str:
    """Render ``table:name | column "Header" format, ...`` as a Markdown table."""
    head, _, spec = body.partition("|")
    name = head.strip()[len("table:"):].strip()
    rows = table(sources.summary, name)
    columns = []
    for item in spec.split(","):
        match = COLUMN.match(item)
        if not match:
            raise FormatError(f"bad column {item.strip()!r} in table {name!r}")
        column, header, form = match.groups()
        format_name, *args = (form or "value").split(":")
        columns.append((column, header or column, format_name, args))
    if not columns or not spec.strip():
        raise FormatError(f"table {name!r} names no columns")
    lines = [
        "| " + " | ".join(header for _, header, _, _ in columns) + " |",
        "|" + "|".join("---" if form == "value" else "---:" for _, _, form, _ in columns) + "|",
    ]
    for index, row in enumerate(rows):
        cells = []
        for column, _, format_name, args in columns:
            if column not in row:
                raise KeyError(f"table {name!r} has no column {column!r}")
            cell = row[column]
            if cell is None:
                cells.append("n/a")
            elif isinstance(cell, bool):
                cells.append("yes" if cell else "no")
            else:
                try:
                    cells.append(formats.apply(format_name, Value(plain=cell), args))
                except FormatError as error:
                    raise FormatError(f"table {name!r} row {index}: {error}") from error
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def render(text: str, sources: Sources, name: str = "template") -> str:
    """Render a template's text; raises :class:`RenderError` listing every problem."""
    problems: list[str] = []
    out_lines = []
    for number, line in enumerate(text.split("\n"), start=1):
        stripped = line.strip()
        block = PLACEHOLDER.fullmatch(stripped)
        if block and block.group(1).strip().startswith("table:"):
            try:
                out_lines.append(render_table(block.group(1), sources))
            except (KeyError, FormatError, ValueError) as error:
                problems.append(f"line {number}: {_message(error)}")
            continue

        def replace(match: re.Match[str], number: int = number) -> str:
            body = match.group(1)
            if body.strip().startswith("table:"):
                problems.append(f"line {number}: a table placeholder must be on its own line")
                return ""
            try:
                return render_value(body, sources)
            except (KeyError, FormatError, ValueError) as error:
                problems.append(f"line {number}: {{{{{body.strip()}}}}}: {_message(error)}")
                return ""

        out_lines.append(PLACEHOLDER.sub(replace, line))
    if "{{" in "\n".join(out_lines) or "}}" in "\n".join(out_lines):
        problems.append("unbalanced placeholder braces")
    if problems:
        raise RenderError(name, problems)
    return "\n".join(out_lines)


def _message(error: Exception) -> str:
    return str(error.args[0]) if isinstance(error, KeyError) and error.args else str(error)


@dataclass(frozen=True)
class Document:
    template: Path
    output: Path

    @property
    def name(self) -> str:
        return self.output.as_posix()


def documents(templates: Path = TEMPLATES) -> list[Document]:
    """Every template and the repository path of the document it produces."""
    return [
        Document(template=path, output=path.relative_to(templates))
        for path in sorted(templates.rglob("*.md"))
    ]


def render_document(document: Document, sources: Sources, root: Path = REPO) -> str:
    """The full text of a rendered document, with the generated-file header."""
    template = document.template
    template_name = (template.relative_to(root).as_posix() if template.is_relative_to(root)
                     else template.name)
    body = render(document.template.read_text(), sources, document.name)
    return HEADER.format(template=template_name) + body


def render_all(sources: Sources, out_root: Path, templates: Path = TEMPLATES,
               root: Path = REPO) -> list[Path]:
    """Render every template into ``out_root``; returns the paths written."""
    written = []
    rendered = {doc: render_document(doc, sources, root) for doc in documents(templates)}
    for doc, text in rendered.items():
        target = out_root / doc.output
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
        written.append(target)
    return written


def out_of_sync(sources: Sources, out_root: Path, templates: Path = TEMPLATES,
                root: Path = REPO) -> list[str]:
    """Documents whose committed text differs from a fresh render."""
    problems = []
    for doc in documents(templates):
        target = out_root / doc.output
        try:
            expected = render_document(doc, sources, root)
        except RenderError as error:
            problems.append(str(error))
            continue
        if not target.exists():
            problems.append(f"{doc.name}: not rendered (run python -m report render)")
        elif target.read_text() != expected:
            problems.append(f"{doc.name}: differs from its template and the results "
                            "(run python -m report render)")
    return problems
