"""Render documents from hand-written templates and the results summary.

A template is Markdown whose numbers come only from placeholders:

``{{ key }}`` or ``{{ key | format }}`` or ``{{ key | format:arg:arg }}``
    a metric in the results summary (``results/summary.json``), printed with a
    format from :mod:`report.formats` (by default the one that fits its unit);
``{{ first.key - second.key | pp }}``
    the difference of two metrics with the same unit (a difference of rates
    prints only as percentage points);
``{{ protocol:windows.test.start | date }}``
    a fixed definition from ``experiments/protocol.yaml``;
``{{ config:world:product.down_payment_bps | bps_pct }}``
    a fixed definition from ``config/<name>.yaml``;
``{{ table:name | column "Header" format, column "Header", ... }}``
    on a line of its own: a generated Markdown table from a result table, with
    the columns named (``format`` optional; ``label`` prints an identifier in
    words, from ``wording.labels`` in ``report/claims.yaml``, and ``id`` prints
    a seed or an order id as it is);
``{{ table:name where col=value ... sum col,col by col,col [across col] | ... }}``
    the same from selected rows of a result table (:func:`select`): ``where``
    keeps the rows whose cell reads ``value``; in the per-world tables of
    :data:`AGGREGABLE`, ``sum`` adds up counts or money over the rows of each
    ``by`` group and ``mean`` averages levels such as a world's median wait, or
    a world's orders, reviews and review minutes (per world, averaged over the
    worlds), each aggregated row with ``rows_count``, the rows it covers;
    ``across`` spreads one column's values into columns holding the sum;
``{{ cell:name [selection] | column format }}``
    inline: the one value of a result table that a selection leaves, with every
    refusal of a table's selection; it fails unless exactly one row remains;
``{{ claim:<id> }}``
    a directional claim from ``report/claims.yaml``, written from its record and
    the results with its evidence (:mod:`report.claims`); it fails to render
    when the results no longer support it;
``{{ fact:<file>:<dotted.path> | format }}``
    a case fact from ``cases/facts/<file>.json`` (a list item by its index), its
    unit from the suffix of the path's last name, like a setting;
``{{ table:fact:<file>:<dotted.path> | column "Header" format, ... }}``
    on a line of its own: a table from a list of records in a case facts file
    (a record without such a value, such as a shipment's amount, holds null and
    prints "n/a", as in result tables);
``{{ facts:<file>:<dotted.path> ["Header" "Header"] | name "Label" format, ... }}``
    on a line of its own: a two-column table of named single values of one
    record in a case facts file, each in its own unit; like ``fact:``, a named
    value that is null fails.

Rendering fails, listing every problem with its line, on a missing key, an
unknown format or a format that does not fit the unit. Templates live under
``report/templates/`` at the path of the document they produce (for example
``report/templates/README.md`` produces ``README.md``).
"""

from __future__ import annotations

import json
import os
import re
import sys
import tempfile
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from core.results import Metric, metric, table
from report import claims as claims_module
from report import formats
from report.claims import is_contrast
from report.formats import FormatError, Value

REPO = Path(__file__).resolve().parent.parent
TEMPLATES = REPO / "report" / "templates"
SUMMARY = REPO / "results" / "summary.json"
FACTS = REPO / "cases" / "facts"
FACT = re.compile(r"^([a-z0-9_]+):([a-z0-9_]+(?:\.[a-z0-9_]+)*)$")
FACTS_HEAD = re.compile(r'^facts:(\S+)(?:\s+"([^"]*)"\s+"([^"]*)")?$')
PLACEHOLDER = re.compile(r"\{\{(.*?)\}\}", re.DOTALL)
COLUMN = re.compile(r'^\s*([a-z0-9_]+)\s*(?:"([^"]*)")?\s*([a-z0-9_:]+)?\s*$')
KEY = re.compile(r"^[a-z0-9_]+(\.[a-z0-9_]+)*$")
HEADER = (
    "<!-- Generated by `python -m report render` from {template}. "
    "Edit the template, not this file. -->\n"
)


class RenderError(ValueError):
    """A template could not be rendered; ``problems`` lists each one."""

    def __init__(self, name: str, problems: list[str]):
        self.problems = problems
        super().__init__(f"{name}: " + "; ".join(problems))


@dataclass
class Sources:
    """Where placeholders look values up."""

    summary: Mapping[str, Any]
    protocol: Mapping[str, Any] = field(default_factory=dict)
    configs: Mapping[str, Mapping[str, Any]] = field(default_factory=dict)
    claims: Mapping[str, claims_module.Claim] = field(default_factory=dict)
    wording: claims_module.Wording | None = None
    facts: Mapping[str, Mapping[str, Any]] = field(default_factory=dict)  # by case file
    labels: Mapping[str, str] = field(default_factory=dict)  # identifier -> words, in tables

    @classmethod
    def from_repo(cls, summary: Mapping[str, Any], root: Path = REPO) -> Sources:
        protocol = yaml.safe_load((root / "experiments" / "protocol.yaml").read_text())
        configs = {
            path.stem: yaml.safe_load(path.read_text())
            for path in sorted((root / "config").glob("*.yaml"))
        }
        claims_file = root / "report" / "claims.yaml"
        claims, wording = claims_module.load_claims(claims_file)
        labels = ((yaml.safe_load(claims_file.read_text()) or {}).get("wording") or {}).get(
            "labels") or {}
        facts = {path.stem: json.loads(path.read_text())
                 for path in sorted((root / "cases" / "facts").glob("*.json"))}
        return cls(summary=summary, protocol=protocol, configs=configs,
                   claims={claim.id: claim for claim in claims}, wording=wording, facts=facts,
                   labels=_labels(labels))


def _path(data: Any, dotted: str, what: str) -> Any:
    node = data
    for part in dotted.split("."):
        if isinstance(node, Mapping) and part in node:
            node = node[part]
        elif isinstance(node, list) and part.isdigit() and int(part) < len(node):
            node = node[int(part)]
        else:
            raise KeyError(f"{what} has no {dotted!r}")
    if isinstance(node, Mapping | list):
        raise KeyError(f"{what} {dotted!r} is not a single value")
    return node


def _fact(expression: str, sources: Sources) -> tuple[Any, str]:
    """The node at ``<file>:<dotted.path>`` in a case facts file, and the path's last name."""
    match = FACT.fullmatch(expression)
    if not match:
        raise KeyError(f"{expression!r} is not <file>:<dotted.path>")
    name, dotted = match.groups()
    if name not in sources.facts:
        raise KeyError(f"no case facts file {name!r} (cases/facts/{name}.json)")
    node: Any = sources.facts[name]
    for part in dotted.split("."):
        if isinstance(node, Mapping) and part in node:
            node = node[part]
        elif isinstance(node, list) and part.isdigit() and int(part) < len(node):
            node = node[int(part)]
        else:
            raise KeyError(f"cases/facts/{name}.json has no {dotted!r}")
    return node, dotted.rsplit(".", 1)[-1]


def _fact_value(expression: str, sources: Sources) -> Value:
    node, last = _fact(expression, sources)
    if isinstance(node, Mapping | list):
        raise KeyError(f"case fact {expression!r} is not a single value")
    if node is None:
        raise KeyError(f"case fact {expression!r} is null")
    return Value(plain=node, unit=formats.unit_from_name(last))


def _resolve(expression: str, sources: Sources) -> Value:
    if expression.startswith("fact:"):
        return _fact_value(expression[len("fact:"):], sources)
    if expression.startswith("protocol:"):
        dotted = expression[len("protocol:"):]
        return _setting(_path(sources.protocol, dotted, "the protocol"), dotted)
    if expression.startswith("config:"):
        name, _, dotted = expression[len("config:"):].partition(":")
        if name not in sources.configs:
            raise KeyError(f"no configuration file {name!r}")
        return _setting(_path(sources.configs[name], dotted, f"config/{name}.yaml"), dotted)
    if " - " in expression:
        first, second = (part.strip() for part in expression.split(" - ", 1))
        return _difference(_metric(first, sources), _metric(second, sources))
    return Value(metric=_metric(expression, sources), contrast=is_contrast(expression))


def _setting(value: Any, dotted: str) -> Value:
    return Value(plain=value, unit=formats.unit_from_name(dotted.rsplit(".", 1)[-1]),
                 setting=True)


def _metric(key: str, sources: Sources) -> Metric:
    if not KEY.fullmatch(key):
        raise KeyError(f"{key!r} is not a result key")
    return metric(sources.summary, key)


def _difference(first: Metric, second: Metric) -> Value:
    if first.unit != second.unit:
        raise FormatError(f"cannot subtract {second.unit} from {first.unit}")
    if not (first.evaluated and second.evaluated):
        raise FormatError("cannot subtract a metric that was not evaluated")
    return Value(plain=first.value - second.value, unit=first.unit, difference=True)


def _split(body: str) -> tuple[str, str, list[str]]:
    expression, _, spec = body.partition("|")
    name, *args = (spec.strip() or "value").split(":")
    return expression.strip(), name.strip(), [arg.strip() for arg in args]


def render_value(body: str, sources: Sources) -> str:
    """Render one inline placeholder body (the text between the braces)."""
    if body.strip().startswith("cell:"):
        return render_cell(body, sources)
    if body.strip().startswith("claim:"):
        claim_id = body.strip()[len("claim:"):].strip()
        if claim_id not in sources.claims or sources.wording is None:
            raise KeyError(f"no claim {claim_id!r} in report/claims.yaml")
        return claims_module.sentence(sources.claims[claim_id], sources.summary, sources.wording)
    expression, name, args = _split(body)
    if name == "p" and (refused := claims_module.selected_reason(expression, sources.summary)):
        raise FormatError(refused)
    return formats.apply(name, _resolve(expression, sources), args)


def render_table(body: str, sources: Sources) -> str:
    """Render ``table:name [selection] | column "Header" format, ...`` as a Markdown table.

    A cell's unit comes from its column name's suffix (``net_cents``,
    ``held_share``, ...), and a column with ``_vs_`` in its name holds paired
    differences (a column spread by ``across`` takes the unit of the column it
    sums); raises :class:`RenderError` listing every problem.
    """
    head, _, spec = body.partition("|")
    name, *clauses = head.strip()[len("table:"):].split() or [""]
    rows = _fact_rows(name[len("fact:"):], sources) if name.startswith("fact:") else \
        table(sources.summary, name)
    units: dict[str, str | None] = {}
    contrasts: set[str] = set()
    if clauses:
        rows, units, contrasts = select(rows, parse_selection(clauses), name,
                                        unevaluated=unevaluated_worlds(sources.summary))
    problems: list[str] = []
    columns = []
    for item in spec.split(",") if spec.strip() else []:
        match = COLUMN.match(item)
        if not match:
            problems.append(f"bad column {item.strip()!r}")
            continue
        column, header, form = match.groups()
        format_name, *args = (form or "value").split(":")
        if format_name not in formats.FORMATS and format_name not in (LABEL, IDENTIFIER):
            problems.append(f"unknown format {format_name!r} for column {column!r}")
        elif rows and column not in rows[0]:
            problems.append(f"no column {column!r}")
        else:
            columns.append((column, header or column, format_name, args))
    if not columns and not problems:
        problems.append("no columns named")
    lines = [
        "| " + " | ".join(header for _, header, _, _ in columns) + " |",
        "|" + "|".join("---" if form in ("value", LABEL, IDENTIFIER) else "---:"
                       for _, _, form, _ in columns) + "|",
    ]
    for index, row in enumerate(rows):
        cells = []
        for column, _, format_name, args in columns:
            try:
                cells.append(_cell(row, column, format_name, args, units, contrasts, sources))
            except FormatError as error:
                problems.append(f"row {index} column {column!r}: {error}")
                cells.append("")
        lines.append("| " + " | ".join(cells) + " |")
    if problems:
        raise RenderError(f"table {name!r}", problems)
    return "\n".join(lines)


def _cell(row: Mapping[str, Any], column: str, format_name: str, args: list[str],
          units: Mapping[str, str | None], contrasts: set[str], sources: Sources) -> str:
    """One value of a result table's row as text; raises :class:`FormatError`."""
    cell = row[column]
    if cell is None:
        return "n/a"
    if isinstance(cell, bool):
        return "yes" if cell else "no"
    if format_name == IDENTIFIER:
        if isinstance(cell, int | str) and not args and formats.unit_from_name(column) is None:
            return str(cell)
        raise FormatError("the id format prints an identifier (a seed, an order id) as it "
                          "is, not a quantity, and takes no arguments")
    if format_name == LABEL:
        if not isinstance(cell, str) or args:
            raise FormatError("the label format takes no arguments and prints identifiers, "
                              "not numbers")
        return label(cell, sources.labels)
    unit = units[column] if column in units else formats.unit_from_name(column)
    return formats.apply(format_name, Value(plain=cell, unit=unit,
                                            contrast="_vs_" in column or column in contrasts),
                         args)


def render_cell(body: str, sources: Sources) -> str:
    """Render ``cell:name [selection] | column format`` inline: the value in ``column`` of
    the one row of the result table ``name`` that the selection leaves (:func:`select`,
    with every refusal it makes for a table); raises :class:`RenderError` unless exactly
    one row remains and one column is named, without a header."""
    head, _, spec = body.partition("|")
    name, *clauses = head.strip()[len("cell:"):].split() or [""]
    where = f"cell {name!r}"
    if name.startswith("fact:"):
        raise RenderError(where, ["a cell comes from a result table; a case fact is fact:"])
    rows = table(sources.summary, name)
    units: dict[str, str | None] = {}
    contrasts: set[str] = set()
    if clauses:
        rows, units, contrasts = select(rows, parse_selection(clauses), name,
                                        unevaluated=unevaluated_worlds(sources.summary))
    match = COLUMN.match(spec) if "," not in spec else None
    if not match or not match.group(1) or match.group(2) is not None:
        raise RenderError(where, ["name one column and its format, without a header: "
                                  "| column format"])
    column, _, form = match.groups()
    format_name, *args = (form or "value").split(":")
    problems = []
    if format_name not in formats.FORMATS and format_name not in (LABEL, IDENTIFIER):
        problems.append(f"unknown format {format_name!r} for column {column!r}")
    if len(rows) != 1:
        problems.append(f"the selection leaves {len(rows)} rows; a cell needs exactly one")
    elif column not in rows[0]:
        problems.append(f"no column {column!r}")
    if problems:
        raise RenderError(where, problems)
    try:
        return _cell(rows[0], column, format_name, args, units, contrasts, sources)
    except FormatError as error:
        raise RenderError(where, [f"column {column!r}: {error}"]) from error


# ---------------------------------------------------------------- selecting rows of a table
LABEL = "label"
IDENTIFIER = "id"  # a seed or an order id in a table, without thousands separators
ROWS_COUNT = "rows_count"
NAME = re.compile(r"^[a-z0-9_]+$")
CLAUSES = ("where", "sum", "mean", "by", "across")
CLAUSE_ORDER = {"where": 0, "sum": 1, "mean": 1, "by": 2, "across": 3}
# The result tables whose rows are per-world values that may be aggregated over worlds,
# and which columns: counts and cents add up (sum); a per-world level with no pooled
# result key, such as a world's median wait, is averaged (mean), and so are a world's
# orders, reviews and review minutes, which have no pooled key either, to give the size
# of one world (per world, averaged over the worlds). Every other table holds
# figures already pooled or averaged over seeds (use their result keys), and every other
# column is refused, so a rate, a share or a mean is never added up or averaged again.
OUTCOME_LEVELS = ("wait_p50_minutes", "wait_p90_minutes", "max_backlog")
OUTCOME_PER_WORLD = ("orders", "reviews", "review_minutes_used", "available_minutes")
OUTCOME_TOTALS = (  # queue_sim.outcomes.OUTCOME_COLUMNS but the levels
    "orders", "gmv_cents", "approved_orders", "approved_gmv_cents",
    "net_cents", "approve_all_net_cents", "net_vs_approve_all_cents",
    "fraud_orders", "fraud_net_cents", "approve_all_fraud_net_cents", "loss_cents",
    "prevented_loss_cents", "credit_loss_orders", "credit_loss_net_cents",
    "legitimate_orders", "legitimate_held", "legitimate_cancelled",
    "legitimate_declined_checkout", "legitimate_blocked_checkout",
    "legitimate_declined_review", "legitimate_declined", "friction_cost_cents",
    "unknown_orders",
    "legitimate_truth_orders", "legitimate_truth_held", "legitimate_truth_cancelled",
    "legitimate_truth_declined_checkout", "legitimate_truth_blocked_checkout",
    "legitimate_truth_declined_review", "legitimate_truth_declined",
    "fraud_declined_checkout", "fraud_stopped_before_shipping", "fraud_declined_after_shipping",
    "review_band", "scored_to_review",
    "reviews", "reviews_decided", "review_minutes_offered", "review_minutes_used",
    "available_minutes", "coverage_minutes", "senior_minutes", "decided_after_shipping",
    "holds", "holds_before_shipping", "checks_run", "escalations", "accounts_blocked",
    "reviews_p0", "reviews_p1", "reviews_p2", "reviews_p3",
    "sla_met_p0", "sla_met_p1", "sla_met_p2", "sla_met_p3",
)
AGGREGABLE: dict[str, dict[str, frozenset[str]]] = {
    "replay.outcomes": {"sum": frozenset(OUTCOME_TOTALS),
                        "mean": frozenset(OUTCOME_LEVELS + OUTCOME_PER_WORLD)},
    "replay.confusion": {"sum": frozenset({"orders"}), "mean": frozenset()},
    "replay.confusion_latent": {"sum": frozenset({"orders"}), "mean": frozenset()},
    "replay.prevented_by_pattern": {
        "sum": frozenset({"orders", "policy_net_cents", "approve_all_net_cents",
                          "prevented_cents"}),
        "mean": frozenset()},
}


@dataclass(frozen=True)
class Selection:
    """The clauses after a table's name: rows kept, then grouped and aggregated."""

    where: tuple[tuple[str, str], ...] = ()
    aggregate: str | None = None  # "sum" or "mean"
    columns: tuple[str, ...] = ()  # the aggregated columns
    by: tuple[str, ...] = ()
    across: str | None = None


def parse_selection(words: list[str]) -> Selection:
    """``where col=value ... [sum|mean col,col by col,col [across col]]``, in that order."""
    found: dict[str, list[str]] = {}
    current = None
    for word in words:
        if word in CLAUSES:
            if current is not None and CLAUSE_ORDER[word] <= CLAUSE_ORDER[current]:
                raise ValueError(f"the {word!r} clause cannot follow {current!r} (the order "
                                 "is where, sum or mean, by, across; each once)")
            current = word
            found[word] = []
        elif current is None:
            raise ValueError(f"{word!r} is not a clause; use where, sum, mean, by or across")
        else:
            found[current].append(word)

    def names(clause: str) -> tuple[str, ...]:
        items = tuple(item.strip() for item in " ".join(found[clause]).split(","))
        if not all(KEY.fullmatch(item) and "." not in item for item in items):
            raise ValueError(f"{clause}: name columns separated by commas, got "
                             f"{' '.join(found[clause])!r}")
        return items

    where = []
    for item in found.get("where", []):
        column, equals, wanted = item.partition("=")
        if not equals or not column or not wanted:
            raise ValueError(f"where: {item!r} is not column=value")
        where.append((column, wanted))
    if "where" in found and not where:
        raise ValueError("where: name at least one column=value")
    aggregate = "sum" if "sum" in found else "mean" if "mean" in found else None
    if aggregate is None and ("by" in found or "across" in found):
        raise ValueError("by and across follow sum or mean")
    if aggregate is not None and "by" not in found:
        raise ValueError(f"{aggregate} needs by: the columns that make a group")
    selection = Selection(
        where=tuple(where), aggregate=aggregate,
        columns=names(aggregate) if aggregate else (),
        by=names("by") if aggregate else (),
        across=None)
    if "across" in found:
        if aggregate != "sum":
            raise ValueError("across spreads a sum, not a mean")
        if len(found["across"]) != 1 or len(selection.columns) != 1:
            raise ValueError("across takes one column, and sums one column")
        selection = Selection(selection.where, aggregate, selection.columns, selection.by,
                              found["across"][0])
    return selection


def _text(cell: Any) -> str:
    """A cell as a where clause reads it."""
    if isinstance(cell, bool):
        return "true" if cell else "false"
    return "null" if cell is None else str(cell)


def aggregation_refused(table_name: str, column: str, how: str) -> str | None:
    """Why ``column`` of the result table ``table_name`` cannot be summed or averaged over
    its rows, or ``None`` (see :data:`AGGREGABLE`)."""
    allowed = AGGREGABLE.get(table_name)
    if allowed is None:
        return (f"{table_name!r} holds figures already pooled or averaged over seeds, or no "
                "per-world values: use its result keys, not a sum or mean of its rows")
    if column in allowed[how]:
        return None
    if how == "sum" and column in allowed["mean"]:
        return f"{column!r} is a per-world level, which does not add up: use mean"
    if how == "mean" and column in allowed["sum"]:
        return (f"{column!r} adds up over worlds: use sum, or its pooled result key for an "
                "average")
    return (f"{column!r} is not a count or money column of {table_name!r} that adds up "
            "over worlds, nor a per-world level")


def _number(cell: Any, column: str) -> int | float | None:
    if cell is None:
        return None
    if isinstance(cell, bool) or not isinstance(cell, int | float):
        raise ValueError(f"column {column!r} holds {cell!r}, not a number")
    return cell


def _aggregate(cells: list[Any], how: str, column: str) -> int | float | None:
    numbers = [_number(cell, column) for cell in cells]
    if any(number is None for number in numbers):
        return None  # a row with nothing measured leaves its group's figure unknown
    total = sum(numbers)
    return total if how == "sum" else total / len(numbers)


WORLD_KEYS = ("seed", "family", "policy")  # a policy's replay of one world


def unevaluated_worlds(summary: Mapping[str, Any]) -> list[dict[str, Any]]:
    """The policies' worlds the replay did not evaluate (``replay.outcomes`` rows with
    ``evaluated`` false: no feasible operating point on that seed), by seed, family and
    policy; the per-world tables hold no rows, or rows of nulls, for them."""
    try:
        rows = table(summary, "replay.outcomes")
    except KeyError:
        return []
    return [{key: row.get(key) for key in WORLD_KEYS} for row in rows
            if row.get("evaluated") is False]


def select(rows: list[dict[str, Any]], selection: Selection, name: str,
           unevaluated: list[dict[str, Any]] = ()
           ) -> tuple[list[dict[str, Any]], dict[str, str | None], set[str]]:
    """The rows ``selection`` keeps and aggregates, the units of spread columns, and
    which of them hold paired differences; raises :class:`RenderError` listing every
    problem.

    An aggregation whose selection reaches a world in ``unevaluated`` (one the ``where``
    clauses on seed, family and policy do not exclude) fails: its total would leave that
    world out, or count its absent rows as zero, without saying so.
    """
    problems = []
    columns = set(rows[0]) if rows else set()
    named = [column for column, _ in selection.where] + list(selection.by) + \
        list(selection.columns) + ([selection.across] if selection.across else [])
    problems += [f"no column {column!r}" for column in dict.fromkeys(named)
                 if column not in columns]
    if selection.aggregate:
        problems += [reason for column in selection.columns
                     if (reason := aggregation_refused(name, column, selection.aggregate))]
        if overlap := set(selection.columns) & set(selection.by):
            problems.append(f"{sorted(overlap)} both group and are aggregated")
        scope = {column: wanted for column, wanted in selection.where if column in WORLD_KEYS}
        for world in unevaluated:
            if all(_text(world.get(column)) == wanted for column, wanted in scope.items()):
                problems.append(
                    f"policy {world.get('policy')!r} was not evaluated on seed "
                    f"{world.get('seed')} ({world.get('family')}), which this selection "
                    "reaches: a total over worlds would leave it out; narrow the selection")
    if problems:
        raise RenderError(f"table {name!r}", problems)
    kept = [row for row in rows
            if all(_text(row.get(column)) == wanted for column, wanted in selection.where)]
    if not kept:
        wanted = " ".join(f"{column}={value}" for column, value in selection.where)
        raise RenderError(f"table {name!r}", [f"no rows match where {wanted}"])
    if not selection.aggregate:
        return kept, {}, set()
    groups: dict[tuple[Any, ...], list[dict[str, Any]]] = {}
    for row in kept:
        groups.setdefault(tuple(row.get(column) for column in selection.by), []).append(row)
    # groups in the order their values first appear in the whole table, so that every
    # selection from one table lists its groups in the same order
    first = [{value: rank for rank, value in
              enumerate(dict.fromkeys(row.get(column) for row in rows))}
             for column in selection.by]
    groups = dict(sorted(groups.items(), key=lambda item: tuple(
        rank[value] for rank, value in zip(first, item[0], strict=True))))
    out = []
    try:
        if selection.across:
            [summed] = selection.columns
            spread = list(dict.fromkeys(row.get(selection.across) for row in kept))
            titles = [_text(value) for value in spread]
            if unnamed := sorted({title for title in titles if not NAME.fullmatch(title)}):
                raise ValueError(f"across {selection.across}: the values {unnamed} cannot "
                                 "name a column (lower-case letters, digits and _)")
            if len(set(titles)) != len(titles):
                raise ValueError(f"across {selection.across}: values that differ print as "
                                 "the same column name")
            if clash := set(titles) & {*selection.by, ROWS_COUNT}:
                raise ValueError(f"spread columns {sorted(clash)} clash with the groups or "
                                 f"{ROWS_COUNT}")
            for key, members in groups.items():
                record = dict(zip(selection.by, key, strict=True))
                for value, title in zip(spread, titles, strict=True):
                    cells = [row.get(summed) for row in members
                             if row.get(selection.across) == value]
                    record[title] = _aggregate(cells, "sum", summed) if cells else 0
                record[ROWS_COUNT] = len(members)
                out.append(record)
            unit = formats.unit_from_name(summed)
            return out, {title: unit for title in titles}, (
                set(titles) if "_vs_" in summed else set())
        for key, members in groups.items():
            record = dict(zip(selection.by, key, strict=True))
            for column in selection.columns:
                record[column] = _aggregate([row.get(column) for row in members],
                                            selection.aggregate, column)
            record[ROWS_COUNT] = len(members)
            out.append(record)
    except ValueError as error:
        raise RenderError(f"table {name!r}", [str(error)]) from error
    return out, {}, set()


def _labels(data: Any) -> dict[str, str]:
    labels = dict(data or {})
    for key, text in labels.items():
        if not isinstance(key, str) or not isinstance(text, str) or not text:
            raise ValueError(f"wording.labels.{key}: give the words as text")
    return labels


def label(identifier: str, labels: Mapping[str, str]) -> str:
    """An identifier, or a comma-separated list of them, in words: its entry in
    ``wording.labels``, else its words split at underscores; an empty list is "none"."""
    if not identifier.strip():
        return "none"
    return ", ".join(labels.get(item, item.replace("_", " "))
                     for item in (part.strip() for part in identifier.split(",")))


def _fact_rows(expression: str, sources: Sources) -> list[dict[str, Any]]:
    node, _ = _fact(expression, sources)
    if not isinstance(node, list) or not all(isinstance(row, Mapping) for row in node):
        raise KeyError(f"case fact {expression!r} is not a list of records")
    return [dict(row) for row in node]


def render_facts(body: str, sources: Sources) -> str:
    """Render ``facts:<file>:<path> ["Header" "Header"] | name "Label" format, ...``: one
    row per named single value of the record at the path, each formatted in the unit of
    its own name; raises :class:`RenderError` listing every problem."""
    head, _, spec = body.partition("|")
    match = FACTS_HEAD.fullmatch(head.strip())
    if not match:
        raise KeyError(f"{head.strip()!r} is not facts:<file>:<dotted.path>")
    expression, first, second = match.groups()
    record, _ = _fact(expression, sources)
    if not isinstance(record, Mapping):
        raise KeyError(f"case fact {expression!r} is not a record")
    problems: list[str] = []
    lines = [f"| {first or 'Fact'} | {second or 'Value'} |", "|---|---:|"]
    for item in spec.split(",") if spec.strip() else []:
        found = COLUMN.match(item)
        if not found:
            problems.append(f"bad entry {item.strip()!r}")
            continue
        key, label, form = found.groups()
        format_name, *args = (form or "value").split(":")
        if format_name not in formats.FORMATS:
            problems.append(f"unknown format {format_name!r} for fact {key!r}")
            continue
        if key not in record:
            problems.append(f"no fact {key!r} in {expression!r}")
            continue
        value = record[key]
        if isinstance(value, Mapping | list):
            problems.append(f"fact {key!r} is not a single value")
            continue
        if value is None:
            problems.append(f"fact {key!r} is null")
            continue
        if isinstance(value, bool):
            if form is not None:
                problems.append(f"fact {key!r} is yes or no and takes no format")
                continue
            cell = "yes" if value else "no"
        else:
            try:
                cell = formats.apply(format_name, Value(plain=value,
                                                        unit=formats.unit_from_name(key)), args)
            except FormatError as error:
                problems.append(f"fact {key!r}: {error}")
                cell = ""
        lines.append(f"| {label or key} | {cell} |")
    if len(lines) == 2 and not problems:
        problems.append("no facts named")
    if problems:
        raise RenderError(f"facts {expression!r}", problems)
    return "\n".join(lines)


def render(text: str, sources: Sources, name: str = "template") -> str:
    """Render a template's text; raises :class:`RenderError` listing every problem."""
    problems: list[str] = []
    out_lines = []
    for number, line in enumerate(text.split("\n"), start=1):
        stripped = line.strip()
        block = PLACEHOLDER.fullmatch(stripped)
        if block and block.group(1).strip().startswith(("table:", "facts:")):
            render_block = render_facts if block.group(1).strip().startswith("facts:") \
                else render_table
            try:
                out_lines.append(render_block(block.group(1), sources))
            except (KeyError, FormatError, ValueError) as error:
                problems.append(f"line {number}: {_message(error)}")
            continue

        def replace(match: re.Match[str], number: int = number) -> str:
            body = match.group(1)
            if body.strip().startswith(("table:", "facts:")):
                problems.append(f"line {number}: a table placeholder must be on its own line")
                return ""
            try:
                return render_value(body, sources)
            except (KeyError, FormatError, ValueError) as error:
                problems.append(f"line {number}: {{{{{body.strip()}}}}}: {_message(error)}")
                return ""

        out_lines.append(PLACEHOLDER.sub(replace, line))
    if "{{" in "\n".join(out_lines) or "}}" in "\n".join(out_lines):
        problems.append("unbalanced placeholder braces")
    if problems:
        raise RenderError(name, problems)
    return "\n".join(out_lines)


def _message(error: Exception) -> str:
    return str(error.args[0]) if isinstance(error, KeyError) and error.args else str(error)


@dataclass(frozen=True)
class Document:
    template: Path
    output: Path

    @property
    def name(self) -> str:
        return self.output.as_posix()


def documents(templates: Path = TEMPLATES) -> list[Document]:
    """Every template and the repository path of the document it produces."""
    return [
        Document(template=path, output=path.relative_to(templates))
        for path in sorted(templates.rglob("*.md"))
    ]


def render_document(document: Document, sources: Sources, root: Path = REPO) -> str:
    """The full text of a rendered document, with the generated-file header."""
    template = document.template
    template_name = (template.relative_to(root).as_posix() if template.is_relative_to(root)
                     else template.name)
    body = render(document.template.read_text(), sources, document.name)
    return HEADER.format(template=template_name) + body


NOT_RENDERED = "NOT_RENDERED.txt"


def render_all(sources: Sources, out_root: Path, templates: Path = TEMPLATES,
               root: Path = REPO, *, strict: bool = False) -> list[Path]:
    """Render every template into ``out_root``; returns the paths written.

    Into the repository (``out_root`` is ``root`` or :data:`REPO`), or with ``strict``,
    a document that cannot be rendered fails the render and nothing is written.
    Anywhere else (a development or small run's ``docs`` folder) the documents whose
    result keys or case facts the run has are written, the others are skipped: they and their
    problems are listed in ``out_root/NOT_RENDERED.txt``, a copy of a skipped
    document left there by an earlier render is removed, and a one-line notice is
    printed. A render that skips nothing removes an old list. A destination that a
    link would carry outside ``out_root`` fails the render before anything is written.
    """
    out_root = Path(out_root)
    strict = strict or is_repository(out_root, root)
    targets = [doc.output for doc in documents(templates)] + [Path(NOT_RENDERED)]
    if escaping := [path.as_posix() for path in targets if not _inside(out_root, path)]:
        raise ValueError(f"{escaping} would be written outside {out_root} through a link; "
                         "nothing was written")
    rendered: dict[Document, str] = {}
    skipped: dict[Document, RenderError] = {}
    for doc in documents(templates):
        try:
            rendered[doc] = render_document(doc, sources, root)
        except RenderError as error:
            if strict:
                raise
            skipped[doc] = error
    written = []
    for doc, text in rendered.items():
        target = out_root / doc.output
        _replace(target, text)
        written.append(target)
    notice = out_root / NOT_RENDERED
    if skipped:
        lines = []
        for doc, error in skipped.items():
            (out_root / doc.output).unlink(missing_ok=True)
            lines += [f"{doc.name}:", *(f"  {problem}" for problem in error.problems)]
        _replace(notice, "Documents not rendered from this summary, and why:\n"
                 + "\n".join(lines) + "\n")
        written.append(notice)
        print(f"report: {len(skipped)} of {len(skipped) + len(rendered)} documents not "
              f"rendered from this summary (see {notice})", file=sys.stderr)
    else:
        notice.unlink(missing_ok=True)
    return written


def _replace(target: Path, text: str) -> None:
    """Write ``text`` to a new file beside ``target`` and move it into place, so a
    destination that shares its contents with another path (a hard link) is replaced,
    never written through."""
    target.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.")
    try:
        with os.fdopen(handle, "w") as stream:
            stream.write(text)
        os.chmod(temporary, 0o644)
        os.replace(temporary, target)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


def is_repository(path: Path, root: Path = REPO) -> bool:
    """Whether ``path`` is the repository (``root`` or :data:`REPO`): the same directory
    on disk, whatever spelling, case or link leads to it."""
    path = Path(path)
    for place in {Path(root), REPO}:
        if path.resolve() == place.resolve():
            return True
        try:
            if path.exists() and place.exists() and path.samefile(place):
                return True
        except OSError:
            continue
    return False


def _inside(out_root: Path, relative: Path) -> bool:
    """Whether ``out_root / relative`` stays under ``out_root`` once links are resolved
    (a folder on the way that links elsewhere would carry writes and removals there)."""
    return (out_root / relative).resolve() == out_root.resolve() / relative


def out_of_sync(sources: Sources, out_root: Path, templates: Path = TEMPLATES,
                root: Path = REPO) -> list[str]:
    """Documents whose committed text differs from a fresh render."""
    problems = []
    for doc in documents(templates):
        target = out_root / doc.output
        try:
            expected = render_document(doc, sources, root)
        except RenderError as error:
            problems.append(str(error))
            continue
        if not target.exists():
            problems.append(f"{doc.name}: not rendered (run python -m report render)")
        elif target.read_text() != expected:
            problems.append(f"{doc.name}: differs from its template and the results "
                            "(run python -m report render)")
    return problems
