services:
  mysql:
    image: mysql:8.4
    container_name: bnpl-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: bnpl
      MYSQL_USER: fraud
      MYSQL_PASSWORD: fraudpw
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pfraudpw", "-ufraud"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  mysql-data:
